//$file${Inc::accel.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: blink.qm
// File:  ${Inc::accel.hpp}
//
// This code has been generated by QM 5.2.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Inc::accel.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef ACCEL_HPP_
#define ACCEL_HPP_

#include "qpcpp.hpp"
#include "signals.hpp"

//$declare${Components::Accel::Accel} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::Accel::Accel} ................................................
class Accel : public QP::QActive {
public:
    static Accel inst;

private:
    QP::QTimeEvt _TimeEvt;

private:
    Accel();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(accel);
    /*
     * Initialise the accelerometer.
     * It is assumed in this project
     * that it will always stay on.
     */
    Q_STATE_DECL(power_up);
    /*
     * Set up the accelerometer
     * with the default settings.
     */
    Q_STATE_DECL(initialise);
    /*
     * The accelerometer only performs
     * background tasks. It is still
     * powered on, but no data is being
     * requested by the application.
     */
    Q_STATE_DECL(idle);
    /*
     * Something happend and the
     * accelerometer is now actively
     * used, for example, by the
     * application. Alternatively,
     * an interrupt may have occurred.
     */
    Q_STATE_DECL(active);
    /*
     * Handle interrupt from
     * accelerometer device.
     * Depending on the source
     * of the interrupt, e.g.,
     * WUP/BTS, TILT, etc., it
     * will post the appropriate
     * event to itself.
     */
    Q_STATE_DECL(handle_irq);
    Q_STATE_DECL(high_watermark);
    Q_STATE_DECL(tilt);
}; // class Accel
//$enddecl${Components::Accel::Accel} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${Components::Accel::AO_Accel} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::Accel::AO_Accel} .............................................
extern QP::QActive * const AO_Accel;
//$enddecl${Components::Accel::AO_Accel} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // ACCEL_HPP_
