//$file${Inc::accel.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: blink.qm
// File:  ${Inc::accel.hpp}
//
// This code has been generated by QM 5.2.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${Inc::accel.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef ACCEL_HPP_
#define ACCEL_HPP_

#include "qpcpp.hpp"
#include "signals.hpp"

//$declare${Components::Accel::Accel} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::Accel::Accel} ................................................
class Accel : public QP::QActive {
public:
    static Accel inst;

private:
    QP::QTimeEvt _TimeEvt;

private:
    Accel();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(accel);
}; // class Accel
//$enddecl${Components::Accel::Accel} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${Components::Accel::AO_Accel} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Components::Accel::AO_Accel} .............................................
extern QP::QActive * const AO_Accel;
//$enddecl${Components::Accel::AO_Accel} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // ACCEL_HPP_
